bot-token: ""
# listening channel
channel-id: ""

# the maximum number of accounts that a user can have
max-num-of-accounts: 1
# if true, users can delete their accounts
allow-delete-accounts: false

database:
  # sqlite, postgres, mysql
  type: sqlite
  name: "DiscordAuth.db"
  # Below is necessary for postgres and mysql
  host: "localhost"
  port: 5432
  username: "user"
  password: "pass"
  ssl: false

activity:
  # WATCHING, LISTENING, PLAYING, COMPETING
  type: PLAYING
  text: "minecraft"

# time to log in (time in seconds)
auth-time: 60